services:
  apache:
    build: ./phpimage
    container_name: website
    ports:
      - 80:80
    volumes:
      - ./website_files:/var/www/html
    depends_on:
      - baza
    restart: unless-stopped
  baza:
    build: ./mariadbimage
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=XAKiRykMqfPy1NMIfrqs
      - MYSQL_DATABASE=sali_libere
      - MYSQL_USER=user
      - MYSQL_PASSWORD=qqGbtlAQxlnHJe4YLjLN
    ports:
      - 3306:3306
    volumes:
      - ./databaseData:/var/lib/mysql
    restart: unless-stopped