services:
  baza:
    build: ./mariadbimage
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=XAKiRykMqfPy1NMIfrqs
      - MYSQL_USER=user
      - MYSQL_PASSWORD=qqGbtlAQxlnHJe4YLjLN
    ports:
      - 3306:3306
    volumes:
      - './databaseData:/var/lib/mysql'
    restart: unless-stopped